/// Flutter icons NabIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NabIcon
///      fonts:
///       - asset: fonts/NabIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NabIcon {
  NabIcon._();

  static const _kFontFam = 'NabIcon';
  static const String? _kFontPkg = null;

  static const IconData heart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartNofill = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeNofill = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profileNofill = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopNofill = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoppingBag = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bagNofill = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
